import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const georgia = localFont({
  src: [
    {
      path: "../../public/fonts/georgia.ttf",
      weight: "400"
    },
    {
      path: "../../public/fonts/georgiab.ttf",
      weight: "700"
    }
  ]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${georgia.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
